Traceback (most recent call last):
  File "/Users/clintguymon/opt/anaconda3/envs/jupiterbook/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/clintguymon/opt/anaconda3/envs/jupiterbook/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/clintguymon/opt/anaconda3/envs/jupiterbook/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/clintguymon/opt/anaconda3/envs/jupiterbook/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/clintguymon/opt/anaconda3/envs/jupiterbook/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/clintguymon/opt/anaconda3/envs/jupiterbook/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/clintguymon/opt/anaconda3/envs/jupiterbook/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
{
    "tags": [
        "hide-output"
    ]

# Simulation parameters
p = ct.one_atm  # pressure [Pa]
Tin = 300.0  # unburned gas temperature [K]
reactants = 'C4H10:1, O2:6.5, N2:24.4'  # premixed gas composition
width = 0.0005  # m
loglevel = 1  # amount of diagnostic output (0 to 8)

# Solution object used to compute mixture properties, set to the state of the
# upstream fuel-air mixture
gas = ct.Solution('sdmech.yaml')
gas.TPX = Tin, p, reactants

# Set up flame object
f = ct.FreeFlame(gas, width=width)
f.set_refine_criteria(ratio=3, slope=0.06, curve=0.12)
#f.show_solution()

# Solve with mixture-averaged transport model
f.transport_model = 'Mix'
f.solve(loglevel=loglevel, auto=True)
#f.show_solution()
}
------------------


[0;36m  Cell [0;32mIn[5], line 7[0;36m[0m
[0;31m    p = ct.one_atm  # pressure [Pa][0m
[0m    ^[0m
[0;31mSyntaxError[0m[0;31m:[0m invalid syntax


